version: '3.8'
services:
  app:
    restart: always
    container_name: app-sicom
    image: "app-sicom:${CI_PIPELINE_ID}"
    build: .
    network_mode: "host"
    dns:
      - 190.90.1.90
      - 190.90.1.91